//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioSeguridad.QA.WCFSeguridadLog
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="coHBase", Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.CoSegur" +
        "idad")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioSeguridad.QA.WCFSeguridadLog.coResultadoDB))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioSeguridad.QA.WCFSeguridadLog.enLogError))]
    public partial class coHBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="coResultadoDB", Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.CoSegur" +
        "idad")]
    public partial class coResultadoDB : ServicioSeguridad.QA.WCFSeguridadLog.coHBase
    {
        
        private string DES_ERRORField;
        
        private string ID_ERRORField;
        
        private int ID_TIPOField;
        
        private int VALORField;
        
        private int VALOR1Field;
        
        private int VALOR10Field;
        
        private int VALOR2Field;
        
        private int VALOR3Field;
        
        private int VALOR4Field;
        
        private int VALOR5Field;
        
        private int VALOR6Field;
        
        private int VALOR7Field;
        
        private int VALOR8Field;
        
        private int VALOR9Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_ERROR
        {
            get
            {
                return this.DES_ERRORField;
            }
            set
            {
                this.DES_ERRORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_ERROR
        {
            get
            {
                return this.ID_ERRORField;
            }
            set
            {
                this.ID_ERRORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TIPO
        {
            get
            {
                return this.ID_TIPOField;
            }
            set
            {
                this.ID_TIPOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VALOR
        {
            get
            {
                return this.VALORField;
            }
            set
            {
                this.VALORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VALOR1
        {
            get
            {
                return this.VALOR1Field;
            }
            set
            {
                this.VALOR1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VALOR10
        {
            get
            {
                return this.VALOR10Field;
            }
            set
            {
                this.VALOR10Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VALOR2
        {
            get
            {
                return this.VALOR2Field;
            }
            set
            {
                this.VALOR2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VALOR3
        {
            get
            {
                return this.VALOR3Field;
            }
            set
            {
                this.VALOR3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VALOR4
        {
            get
            {
                return this.VALOR4Field;
            }
            set
            {
                this.VALOR4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VALOR5
        {
            get
            {
                return this.VALOR5Field;
            }
            set
            {
                this.VALOR5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VALOR6
        {
            get
            {
                return this.VALOR6Field;
            }
            set
            {
                this.VALOR6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VALOR7
        {
            get
            {
                return this.VALOR7Field;
            }
            set
            {
                this.VALOR7Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VALOR8
        {
            get
            {
                return this.VALOR8Field;
            }
            set
            {
                this.VALOR8Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VALOR9
        {
            get
            {
                return this.VALOR9Field;
            }
            set
            {
                this.VALOR9Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="enLogError", Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.EnSegur" +
        "idad")]
    public partial class enLogError : ServicioSeguridad.QA.WCFSeguridadLog.coHBase
    {
        
        private string COD_FUENTEField;
        
        private string COD_LOGField;
        
        private string DES_ERRORField;
        
        private string DES_ESQField;
        
        private string DES_FUENTEField;
        
        private string DES_PAGINAOBJETOField;
        
        private string DES_PREFIJOField;
        
        private string DES_SISField;
        
        private System.DateTime FEC_CREAField;
        
        private System.DateTime FEC_FINField;
        
        private int ID_LOGERRORField;
        
        private int ID_SISField;
        
        private string IP_CREAField;
        
        private string NOM_USUField;
        
        private string OPRField;
        
        private int USU_CREAField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_FUENTE
        {
            get
            {
                return this.COD_FUENTEField;
            }
            set
            {
                this.COD_FUENTEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_LOG
        {
            get
            {
                return this.COD_LOGField;
            }
            set
            {
                this.COD_LOGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_ERROR
        {
            get
            {
                return this.DES_ERRORField;
            }
            set
            {
                this.DES_ERRORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_ESQ
        {
            get
            {
                return this.DES_ESQField;
            }
            set
            {
                this.DES_ESQField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_FUENTE
        {
            get
            {
                return this.DES_FUENTEField;
            }
            set
            {
                this.DES_FUENTEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_PAGINAOBJETO
        {
            get
            {
                return this.DES_PAGINAOBJETOField;
            }
            set
            {
                this.DES_PAGINAOBJETOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_PREFIJO
        {
            get
            {
                return this.DES_PREFIJOField;
            }
            set
            {
                this.DES_PREFIJOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_SIS
        {
            get
            {
                return this.DES_SISField;
            }
            set
            {
                this.DES_SISField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FEC_CREA
        {
            get
            {
                return this.FEC_CREAField;
            }
            set
            {
                this.FEC_CREAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FEC_FIN
        {
            get
            {
                return this.FEC_FINField;
            }
            set
            {
                this.FEC_FINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_LOGERROR
        {
            get
            {
                return this.ID_LOGERRORField;
            }
            set
            {
                this.ID_LOGERRORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_SIS
        {
            get
            {
                return this.ID_SISField;
            }
            set
            {
                this.ID_SISField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP_CREA
        {
            get
            {
                return this.IP_CREAField;
            }
            set
            {
                this.IP_CREAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_USU
        {
            get
            {
                return this.NOM_USUField;
            }
            set
            {
                this.NOM_USUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OPR
        {
            get
            {
                return this.OPRField;
            }
            set
            {
                this.OPRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int USU_CREA
        {
            get
            {
                return this.USU_CREAField;
            }
            set
            {
                this.USU_CREAField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioSeguridad.QA.WCFSeguridadLog.IWCFSeguridadLog")]
    public interface IWCFSeguridadLog
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSeguridadLog/log", ReplyAction="http://tempuri.org/IWCFSeguridadLog/logResponse")]
        System.Threading.Tasks.Task<ServicioSeguridad.QA.WCFSeguridadLog.coResultadoDB> logAsync(ServicioSeguridad.QA.WCFSeguridadLog.enLogError oEnLogError);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IWCFSeguridadLogChannel : ServicioSeguridad.QA.WCFSeguridadLog.IWCFSeguridadLog, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WCFSeguridadLogClient : System.ServiceModel.ClientBase<ServicioSeguridad.QA.WCFSeguridadLog.IWCFSeguridadLog>, ServicioSeguridad.QA.WCFSeguridadLog.IWCFSeguridadLog
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WCFSeguridadLogClient() : 
                base(WCFSeguridadLogClient.GetDefaultBinding(), WCFSeguridadLogClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWCFSeguridadLog.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFSeguridadLogClient(EndpointConfiguration endpointConfiguration) : 
                base(WCFSeguridadLogClient.GetBindingForEndpoint(endpointConfiguration), WCFSeguridadLogClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFSeguridadLogClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WCFSeguridadLogClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFSeguridadLogClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WCFSeguridadLogClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFSeguridadLogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServicioSeguridad.QA.WCFSeguridadLog.coResultadoDB> logAsync(ServicioSeguridad.QA.WCFSeguridadLog.enLogError oEnLogError)
        {
            return base.Channel.logAsync(oEnLogError);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWCFSeguridadLog))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWCFSeguridadLog))
            {
                return new System.ServiceModel.EndpointAddress("http://svcqa.mincetur.gob.pe/servicioSeguridad/WCFSeguridadLog.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WCFSeguridadLogClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWCFSeguridadLog);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WCFSeguridadLogClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWCFSeguridadLog);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWCFSeguridadLog,
        }
    }
}
