//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioPide.QA.WCFPideMigraCarnetExtranjeria
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="solicitudBean", Namespace="Mincetur.Administracion.Wrapper.ServicioPideMigraciones")]
    public partial class solicitudBean : object
    {
        
        private string strNumDocumentoFieldField;
        
        private string strTipoDocumentoFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strNumDocumentoField
        {
            get
            {
                return this.strNumDocumentoFieldField;
            }
            set
            {
                this.strNumDocumentoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strTipoDocumentoField
        {
            get
            {
                return this.strTipoDocumentoFieldField;
            }
            set
            {
                this.strTipoDocumentoFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="respuestaBean", Namespace="Mincetur.Administracion.Wrapper.ServicioPideMigraciones")]
    public partial class respuestaBean : object
    {
        
        private string strCalidadMigratoriaFieldField;
        
        private string strNombresFieldField;
        
        private string strNumRespuestaFieldField;
        
        private string strPrimerApellidoFieldField;
        
        private string strSegundoApellidoFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strCalidadMigratoriaField
        {
            get
            {
                return this.strCalidadMigratoriaFieldField;
            }
            set
            {
                this.strCalidadMigratoriaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strNombresField
        {
            get
            {
                return this.strNombresFieldField;
            }
            set
            {
                this.strNombresFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strNumRespuestaField
        {
            get
            {
                return this.strNumRespuestaFieldField;
            }
            set
            {
                this.strNumRespuestaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strPrimerApellidoField
        {
            get
            {
                return this.strPrimerApellidoFieldField;
            }
            set
            {
                this.strPrimerApellidoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strSegundoApellidoField
        {
            get
            {
                return this.strSegundoApellidoFieldField;
            }
            set
            {
                this.strSegundoApellidoFieldField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioPide.QA.WCFPideMigraCarnetExtranjeria.IWCFPideMigraCarnetExtranjeria")]
    public interface IWCFPideMigraCarnetExtranjeria
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFPideMigraCarnetExtranjeria/consultarDocumento", ReplyAction="http://tempuri.org/IWCFPideMigraCarnetExtranjeria/consultarDocumentoResponse")]
        System.Threading.Tasks.Task<ServicioPide.QA.WCFPideMigraCarnetExtranjeria.respuestaBean> consultarDocumentoAsync(ServicioPide.QA.WCFPideMigraCarnetExtranjeria.solicitudBean solicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IWCFPideMigraCarnetExtranjeriaChannel : ServicioPide.QA.WCFPideMigraCarnetExtranjeria.IWCFPideMigraCarnetExtranjeria, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WCFPideMigraCarnetExtranjeriaClient : System.ServiceModel.ClientBase<ServicioPide.QA.WCFPideMigraCarnetExtranjeria.IWCFPideMigraCarnetExtranjeria>, ServicioPide.QA.WCFPideMigraCarnetExtranjeria.IWCFPideMigraCarnetExtranjeria
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WCFPideMigraCarnetExtranjeriaClient() : 
                base(WCFPideMigraCarnetExtranjeriaClient.GetDefaultBinding(), WCFPideMigraCarnetExtranjeriaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWCFPideMigraCarnetExtranjeria.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFPideMigraCarnetExtranjeriaClient(EndpointConfiguration endpointConfiguration) : 
                base(WCFPideMigraCarnetExtranjeriaClient.GetBindingForEndpoint(endpointConfiguration), WCFPideMigraCarnetExtranjeriaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFPideMigraCarnetExtranjeriaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WCFPideMigraCarnetExtranjeriaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFPideMigraCarnetExtranjeriaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WCFPideMigraCarnetExtranjeriaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFPideMigraCarnetExtranjeriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServicioPide.QA.WCFPideMigraCarnetExtranjeria.respuestaBean> consultarDocumentoAsync(ServicioPide.QA.WCFPideMigraCarnetExtranjeria.solicitudBean solicitud)
        {
            return base.Channel.consultarDocumentoAsync(solicitud);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWCFPideMigraCarnetExtranjeria))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWCFPideMigraCarnetExtranjeria))
            {
                return new System.ServiceModel.EndpointAddress("http://wseqa.mincetur.gob.pe/ServicioPide/Migra/Services/WCFPideMigraCarnetExtran" +
                        "jeria.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WCFPideMigraCarnetExtranjeriaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWCFPideMigraCarnetExtranjeria);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WCFPideMigraCarnetExtranjeriaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWCFPideMigraCarnetExtranjeria);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWCFPideMigraCarnetExtranjeria,
        }
    }
}
